
INSERT INTO public.playground_prompts (user_id, name, prompt_text, tags, task_type, is_standard) VALUES
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Skin texture close-up', 'Close-up portrait of a 30-year-old woman, natural light from a north-facing window, visible skin pores and fine peach fuzz on cheeks, no makeup, shallow depth of field, Canon EF 100mm f/2.8L Macro', ARRAY['anatomy', 'texture', 'portrait'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Hand anatomy test', 'A pianist''s hands resting on ivory keys, fingers slightly curved, visible tendons and natural nail beds, soft overhead stage lighting, photorealistic, 8K detail', ARRAY['anatomy', 'lighting'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Multi-subject interaction', 'Two women sitting at a Parisian café table, one leaning forward whispering, the other laughing with head tilted back, espresso cups between them, golden hour backlighting through the window', ARRAY['multi-subject', 'spatial', 'lighting'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Aerial architecture', 'Aerial drone photograph of a spiral-shaped museum building surrounded by cherry blossom trees in full bloom, late afternoon shadows creating geometric patterns on the plaza, 4K', ARRAY['spatial', 'architecture', 'landscape'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Dramatic studio lighting', 'Full body portrait of a male dancer mid-leap, single hard spotlight from camera-left creating deep shadows, muscular definition visible, motion blur on extremities, black background, Hasselblad medium format', ARRAY['lighting', 'anatomy', 'action'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'HEX color accuracy', 'Fashion editorial: model wearing a tailored blazer in exact color #C41E3A (cardinal red) against a wall painted #1B4D3E (dark emerald green), neutral makeup, sharp focus, Vogue aesthetic', ARRAY['color', 'portrait'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Reflective materials', 'Still life of a chrome espresso machine reflecting a kitchen window, water droplets on the metal surface, morning light creating caustic patterns, hyperrealistic, product photography', ARRAY['texture', 'lighting'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Text rendering', 'A weathered wooden sign reading "OPEN DAILY 9-5" in hand-painted serif letters, slightly faded, mounted on a rustic brick wall with ivy growing around the edges, natural daylight', ARRAY['text', 'texture'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Complex composition', 'A busy Tokyo street crossing at night, neon signs in Japanese and English, crowd of 8-10 people mid-stride each with distinct clothing and posture, wet pavement reflecting lights, cinematic 35mm', ARRAY['spatial', 'multi-subject', 'lighting'], 't2i', true),
('3348b481-8fb1-4745-8e6c-db6e9847e429', 'Fine detail & bokeh', 'Extreme close-up of a monarch butterfly perched on a lavender stem, compound eye facets visible, wing scales iridescent in sunlight, creamy bokeh background of a meadow, macro lens f/2.8', ARRAY['texture', 'anatomy'], 't2i', true);
