// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulmdmzhcdwfadbvfpckt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbWRtemhjZHdmYWRidmZwY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzgxMTAsImV4cCI6MjA2MTM1NDExMH0.5PDD2tTcdJz_n6f-GbMCPDH7ocrEbKYShCPKkApnTQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);